export const POKEMONS: {
  no: string;
  name: string;
  version: number;
  name2?: string;
  name3?: string;
  isMega?: boolean;
  isGigantic?: boolean;
  isRegion?: boolean;
  isAnotherForm?: boolean;
  anotherAnswer?: { name: string; name2?: string; name3?: string };
}[] = [
  { no: "1", name: "フシギダネ", version: 1 },
  { no: "2", name: "フシギソウ", version: 1 },
  { no: "3", name: "フシギバナ", version: 1 },
  { no: "3-1", name: "メガフシギバナ", version: 1, isMega: true },
  {
    no: "3-2",
    name: "フシギバナ",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "4", name: "ヒトカゲ", version: 1 },
  { no: "5", name: "リザード", version: 1 },
  { no: "6", name: "リザードン", version: 1 },
  { no: "6-1", name: "メガリザードンX", version: 1, isMega: true },
  { no: "6-2", name: "メガリザードンY", version: 1, isMega: true },
  {
    no: "6-3",
    name: "リザードン",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "7", name: "ゼニガメ", version: 1 },
  { no: "8", name: "カメール", version: 1 },
  { no: "9", name: "カメックス", version: 1 },
  { no: "9-1", name: "メガカメックス", version: 1, isMega: true },
  {
    no: "9-2",
    name: "カメックス",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "10", name: "キャタピー", version: 1 },
  { no: "11", name: "トランセル", version: 1 },
  { no: "12", name: "バタフリー", version: 1 },
  {
    no: "12-1",
    name: "バタフリー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "13", name: "ビードル", version: 1 },
  { no: "14", name: "コクーン", version: 1 },
  { no: "15", name: "スピアー", version: 1 },
  { no: "15-1", name: "メガスピアー", version: 1, isMega: true },
  { no: "16", name: "ポッポ", version: 1 },
  { no: "17", name: "ピジョン", version: 1 },
  { no: "18", name: "ピジョット", version: 1 },
  { no: "18-1", name: "メガピジョット", version: 1, isMega: true },
  { no: "19", name: "コラッタ", version: 1 },
  {
    no: "19-1",
    name: "コラッタ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "20", name: "ラッタ", version: 1 },
  {
    no: "20-1",
    name: "ラッタ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "21", name: "オニスズメ", version: 1 },
  { no: "22", name: "オニドリル", version: 1 },
  { no: "23", name: "アーボ", version: 1 },
  { no: "24", name: "アーボック", version: 1 },
  { no: "25", name: "ピカチュウ", version: 1 },
  {
    no: "25-1",
    name: "ピカチュウ",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "26", name: "ライチュウ", version: 1 },
  {
    no: "26-1",
    name: "ライチュウ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "27", name: "サンド", version: 1 },
  {
    no: "27-1",
    name: "サンド",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "28", name: "サンドパン", version: 1 },
  {
    no: "28-1",
    name: "サンドパン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  {
    no: "29",
    name: "ニドラン♀",
    version: 1,
    anotherAnswer: { name: "ニドランメス" },
  },
  { no: "30", name: "ニドリーナ", version: 1 },
  { no: "31", name: "ニドクイン", version: 1 },
  {
    no: "32",
    name: "ニドラン♂",
    version: 1,
    anotherAnswer: { name: "ニドランオス" },
  },
  { no: "33", name: "ニドリーノ", version: 1 },
  { no: "34", name: "ニドキング", version: 1 },
  { no: "35", name: "ピッピ", version: 1 },
  { no: "36", name: "ピクシー", version: 1 },
  { no: "37", name: "ロコン", version: 1 },
  {
    no: "37-1",
    name: "ロコン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "38", name: "キュウコン", version: 1 },
  {
    no: "38-1",
    name: "キュウコン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "39", name: "プリン", version: 1 },
  { no: "40", name: "プクリン", version: 1 },
  { no: "41", name: "ズバット", version: 1 },
  { no: "42", name: "ゴルバット", version: 1 },
  { no: "43", name: "ナゾノクサ", version: 1 },
  { no: "44", name: "クサイハナ", version: 1 },
  { no: "45", name: "ラフレシア", version: 1 },
  { no: "46", name: "パラス", version: 1 },
  { no: "47", name: "パラセクト", version: 1 },
  { no: "48", name: "コンパン", version: 1 },
  { no: "49", name: "モルフォン", version: 1 },
  { no: "50", name: "ディグダ", version: 1 },
  {
    no: "50-1",
    name: "ディグダ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "51", name: "ダグトリオ", version: 1 },
  {
    no: "51-1",
    name: "ダグトリオ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "52", name: "ニャース", version: 1 },
  {
    no: "52-1",
    name: "ニャース",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  {
    no: "52-2",
    name: "ニャース",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  {
    no: "52-3",
    name: "ニャース",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "53", name: "ペルシアン", version: 1 },
  {
    no: "53-1",
    name: "ペルシアン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "54", name: "コダック", version: 1 },
  { no: "55", name: "ゴルダック", version: 1 },
  { no: "56", name: "マンキー", version: 1 },
  { no: "57", name: "オコリザル", version: 1 },
  { no: "58", name: "ガーディ", version: 1 },
  {
    no: "58-1",
    name: "ガーディ",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "59", name: "ウインディ", version: 1 },
  {
    no: "59-1",
    name: "ウインディ",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "60", name: "ニョロモ", version: 1 },
  { no: "61", name: "ニョロゾ", version: 1 },
  { no: "62", name: "ニョロボン", version: 1 },
  { no: "63", name: "ケーシィ", version: 1 },
  { no: "64", name: "ユンゲラー", version: 1 },
  { no: "65", name: "フーディン", version: 1 },
  { no: "65-1", name: "メガフーディン", version: 1, isMega: true },
  { no: "66", name: "ワンリキー", version: 1 },
  { no: "67", name: "ゴーリキー", version: 1 },
  { no: "68", name: "カイリキー", version: 1 },
  {
    no: "68-1",
    name: "カイリキー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "69", name: "マダツボミ", version: 1 },
  { no: "70", name: "ウツドン", version: 1 },
  { no: "71", name: "ウツボット", version: 1 },
  { no: "72", name: "メノクラゲ", version: 1 },
  { no: "73", name: "ドククラゲ", version: 1 },
  { no: "74", name: "イシツブテ", version: 1 },
  {
    no: "74-1",
    name: "イシツブテ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "75", name: "ゴローン", version: 1 },
  {
    no: "75-1",
    name: "ゴローン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "76", name: "ゴローニャ", version: 1 },
  {
    no: "76-1",
    name: "ゴローニャ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "77", name: "ポニータ", version: 1 },
  {
    no: "77-1",
    name: "ポニータ",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "78", name: "ギャロップ", version: 1 },
  {
    no: "78-1",
    name: "ギャロップ",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "79", name: "ヤドン", version: 1 },
  {
    no: "79-1",
    name: "ヤドン",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "80", name: "ヤドラン", version: 1 },
  {
    no: "80-1",
    name: "ヤドラン",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "80-2", name: "メガヤドラン", version: 1, isMega: true },
  { no: "81", name: "コイル", version: 1 },
  { no: "82", name: "レアコイル", version: 1 },
  { no: "83", name: "カモネギ", version: 1 },
  {
    no: "83-1",
    name: "カモネギ",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "84", name: "ドードー", version: 1 },
  { no: "85", name: "ドードリオ", version: 1 },
  { no: "86", name: "パウワウ", version: 1 },
  { no: "87", name: "ジュゴン", version: 1 },
  { no: "88", name: "ベトベター", version: 1 },
  {
    no: "88-1",
    name: "ベトベター",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "89", name: "ベトベトン", version: 1 },
  {
    no: "89-1",
    name: "ベトベトン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "90", name: "シェルダー", version: 1 },
  { no: "91", name: "パルシェン", version: 1 },
  { no: "92", name: "ゴース", version: 1 },
  { no: "93", name: "ゴースト", version: 1 },
  { no: "94", name: "ゲンガー", version: 1 },
  { no: "94-1", name: "メガゲンガー", version: 1, isMega: true },
  {
    no: "94-2",
    name: "ゲンガー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "95", name: "イワーク", version: 1 },
  { no: "96", name: "スリープ", version: 1 },
  { no: "97", name: "スリーパー", version: 1 },
  { no: "98", name: "クラブ", version: 1 },
  { no: "99", name: "キングラー", version: 1 },
  {
    no: "99-1",
    name: "キングラー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "100", name: "ビリリダマ", version: 1 },
  {
    no: "100-1",
    name: "ビリリダマ",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "101", name: "マルマイン", version: 1 },
  {
    no: "101-1",
    name: "マルマイン",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "102", name: "タマタマ", version: 1 },
  { no: "103", name: "ナッシー", version: 1 },
  {
    no: "103-1",
    name: "ナッシー",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "104", name: "カラカラ", version: 1 },
  { no: "105", name: "ガラガラ", version: 1 },
  {
    no: "105-1",
    name: "ガラガラ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "106", name: "サワムラー", version: 1 },
  { no: "107", name: "エビワラー", version: 1 },
  { no: "108", name: "ベロリンガ", version: 1 },
  { no: "109", name: "ドガース", version: 1 },
  { no: "110", name: "マタドガス", version: 1 },
  {
    no: "110-1",
    name: "マタドガス",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "111", name: "サイホーン", version: 1 },
  { no: "112", name: "サイドン", version: 1 },
  { no: "113", name: "ラッキー", version: 1 },
  { no: "114", name: "モンジャラ", version: 1 },
  { no: "115", name: "ガルーラ", version: 1 },
  { no: "115-1", name: "メガガルーラ", version: 1, isMega: true },
  { no: "116", name: "タッツー", version: 1 },
  { no: "117", name: "シードラ", version: 1 },
  { no: "118", name: "トサキント", version: 1 },
  { no: "119", name: "アズマオウ", version: 1 },
  { no: "120", name: "ヒトデマン", version: 1 },
  { no: "121", name: "スターミー", version: 1 },
  { no: "122", name: "バリヤード", version: 1 },
  {
    no: "122-1",
    name: "バリヤード",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "123", name: "ストライク", version: 1 },
  { no: "124", name: "ルージュラ", version: 1 },
  { no: "125", name: "エレブー", version: 1 },
  { no: "126", name: "ブーバー", version: 1 },
  { no: "127", name: "カイロス", version: 1 },
  { no: "127-1", name: "メガカイロス", version: 1, isMega: true },
  { no: "128", name: "ケンタロス", version: 1 },
  {
    no: "128-1",
    name: "ケンタロス",
    name2: "パルデアのすがた",
    name3: "コンバットしゅ",
    version: 1,
    isRegion: true,
    isAnotherForm: true,
  },
  {
    no: "128-2",
    name: "ケンタロス",
    name2: "パルデアのすがた",
    name3: "ブレイズしゅ",
    version: 1,
    isRegion: true,
    isAnotherForm: true,
  },
  {
    no: "128-3",
    name: "ケンタロス",
    name2: "パルデアのすがた",
    name3: "ウォーターしゅ",
    version: 1,
    isRegion: true,
    isAnotherForm: true,
  },
  { no: "129", name: "コイキング", version: 1 },
  { no: "130", name: "ギャラドス", version: 1 },
  { no: "130-1", name: "メガギャラドス", version: 1, isMega: true },
  { no: "131", name: "ラプラス", version: 1 },
  {
    no: "131-1",
    name: "ラプラス",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "132", name: "メタモン", version: 1 },
  { no: "133", name: "イーブイ", version: 1 },
  {
    no: "133-1",
    name: "イーブイ",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "134", name: "シャワーズ", version: 1 },
  { no: "135", name: "サンダース", version: 1 },
  { no: "136", name: "ブースター", version: 1 },
  { no: "137", name: "ポリゴン", version: 1 },
  { no: "138", name: "オムナイト", version: 1 },
  { no: "139", name: "オムスター", version: 1 },
  { no: "140", name: "カブト", version: 1 },
  { no: "141", name: "カブトプス", version: 1 },
  { no: "142", name: "プテラ", version: 1 },
  { no: "142-1", name: "メガプテラ", version: 1, isMega: true },
  { no: "143", name: "カビゴン", version: 1 },
  {
    no: "143-1",
    name: "カビゴン",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "144", name: "フリーザー", version: 1 },
  {
    no: "144-1",
    name: "フリーザー",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "145", name: "サンダー", version: 1 },
  {
    no: "145-1",
    name: "サンダー",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "146", name: "ファイヤー", version: 1 },
  {
    no: "146-1",
    name: "ファイヤー",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "147", name: "ミニリュウ", version: 1 },
  { no: "148", name: "ハクリュー", version: 1 },
  { no: "149", name: "カイリュー", version: 1 },
  { no: "150", name: "ミュウツー", version: 1 },
  { no: "150-1", name: "メガミュウツーX", version: 1, isMega: true },
  { no: "150-2", name: "メガミュウツーY", version: 1, isMega: true },
  { no: "151", name: "ミュウ", version: 1 },
  { no: "152", name: "チコリータ", version: 2 },
  { no: "153", name: "ベイリーフ", version: 2 },
  { no: "154", name: "メガニウム", version: 2 },
  { no: "155", name: "ヒノアラシ", version: 2 },
  { no: "156", name: "マグマラシ", version: 2 },
  { no: "157", name: "バクフーン", version: 2 },
  {
    no: "157-1",
    name: "バクフーン",
    name2: "ヒスイのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "158", name: "ワニノコ", version: 2 },
  { no: "159", name: "アリゲイツ", version: 2 },
  { no: "160", name: "オーダイル", version: 2 },
  { no: "161", name: "オタチ", version: 2 },
  { no: "162", name: "オオタチ", version: 2 },
  { no: "163", name: "ホーホー", version: 2 },
  { no: "164", name: "ヨルノズク", version: 2 },
  { no: "165", name: "レディバ", version: 2 },
  { no: "166", name: "レディアン", version: 2 },
  { no: "167", name: "イトマル", version: 2 },
  { no: "168", name: "アリアドス", version: 2 },
  { no: "169", name: "クロバット", version: 2 },
  { no: "170", name: "チョンチー", version: 2 },
  { no: "171", name: "ランターン", version: 2 },
  { no: "172", name: "ピチュー", version: 2 },
  { no: "173", name: "ピィ", version: 2 },
  { no: "174", name: "ププリン", version: 2 },
  { no: "175", name: "トゲピー", version: 2 },
  { no: "176", name: "トゲチック", version: 2 },
  { no: "177", name: "ネイティ", version: 2 },
  { no: "178", name: "ネイティオ", version: 2 },
  { no: "179", name: "メリープ", version: 2 },
  { no: "180", name: "モココ", version: 2 },
  { no: "181", name: "デンリュウ", version: 2 },
  { no: "181-1", name: "メガデンリュウ", version: 2, isMega: true },
  { no: "182", name: "キレイハナ", version: 2 },
  { no: "183", name: "マリル", version: 2 },
  { no: "184", name: "マリルリ", version: 2 },
  { no: "185", name: "ウソッキー", version: 2 },
  { no: "186", name: "ニョロトノ", version: 2 },
  { no: "187", name: "ハネッコ", version: 2 },
  { no: "188", name: "ポポッコ", version: 2 },
  { no: "189", name: "ワタッコ", version: 2 },
  { no: "190", name: "エイパム", version: 2 },
  { no: "191", name: "ヒマナッツ", version: 2 },
  { no: "192", name: "キマワリ", version: 2 },
  { no: "193", name: "ヤンヤンマ", version: 2 },
  { no: "194", name: "ウパー", version: 2 },
  {
    no: "194-1",
    name: "ウパー",
    name2: "パルデアのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "195", name: "ヌオー", version: 2 },
  { no: "196", name: "エーフィ", version: 2 },
  { no: "197", name: "ブラッキー", version: 2 },
  { no: "198", name: "ヤミカラス", version: 2 },
  { no: "199", name: "ヤドキング", version: 2 },
  {
    no: "199-1",
    name: "ヤドキング",
    name2: "ガラルのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "200", name: "ムウマ", version: 2 },
  { no: "201", name: "アンノーン", version: 2 },
  { no: "202", name: "ソーナンス", version: 2 },
  { no: "203", name: "キリンリキ", version: 2 },
  { no: "204", name: "クヌギダマ", version: 2 },
  { no: "205", name: "フォレトス", version: 2 },
  { no: "206", name: "ノコッチ", version: 2 },
  { no: "207", name: "グライガー", version: 2 },
  { no: "208", name: "ハガネール", version: 2 },
  { no: "208-1", name: "メガハガネール", version: 2, isMega: true },
  { no: "209", name: "ブルー", version: 2 },
  { no: "210", name: "グランブル", version: 2 },
  { no: "211", name: "ハリーセン", version: 2 },
  {
    no: "211-1",
    name: "ハリーセン",
    name2: "ヒスイのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "212", name: "ハッサム", version: 2 },
  { no: "212-1", name: "メガハッサム", version: 2, isMega: true },
  { no: "213", name: "ツボツボ", version: 2 },
  { no: "214", name: "ヘラクロス", version: 2 },
  { no: "214-1", name: "メガヘラクロス", version: 2, isMega: true },
  { no: "215", name: "ニューラ", version: 2 },
  {
    no: "215-1",
    name: "ニューラ",
    name2: "ヒスイのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "216", name: "ヒメグマ", version: 2 },
  { no: "217", name: "リングマ", version: 2 },
  { no: "218", name: "マグマッグ", version: 2 },
  { no: "219", name: "マグカルゴ", version: 2 },
  { no: "220", name: "ウリムー", version: 2 },
  { no: "221", name: "イノムー", version: 2 },
  { no: "222", name: "サニーゴ", version: 2 },
  {
    no: "222-1",
    name: "サニーゴ",
    name2: "ガラルのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "223", name: "テッポウオ", version: 2 },
  { no: "224", name: "オクタン", version: 2 },
  { no: "225", name: "デリバード", version: 2 },
  { no: "226", name: "マンタイン", version: 2 },
  { no: "227", name: "エアームド", version: 2 },
  { no: "228", name: "デルビル", version: 2 },
  { no: "229", name: "ヘルガー", version: 2 },
  { no: "229-1", name: "メガヘルガー", version: 2, isMega: true },
  { no: "230", name: "キングドラ", version: 2 },
  { no: "231", name: "ゴマゾウ", version: 2 },
  { no: "232", name: "ドンファン", version: 2 },
  {
    no: "233",
    name: "ポリゴン2",
    version: 2,
    anotherAnswer: { name: "ポリゴンツー" },
  },
  { no: "234", name: "オドシシ", version: 2 },
  { no: "235", name: "ドーブル", version: 2 },
  { no: "236", name: "バルキー", version: 2 },
  { no: "237", name: "カポエラー", version: 2 },
  { no: "238", name: "ムチュール", version: 2 },
  { no: "239", name: "エレキッド", version: 2 },
  { no: "240", name: "ブビィ", version: 2 },
  { no: "241", name: "ミルタンク", version: 2 },
  { no: "242", name: "ハピナス", version: 2 },
  { no: "243", name: "ライコウ", version: 2 },
  { no: "244", name: "エンテイ", version: 2 },
  { no: "245", name: "スイクン", version: 2 },
  { no: "246", name: "ヨーギラス", version: 2 },
  { no: "247", name: "サナギラス", version: 2 },
  { no: "248", name: "バンギラス", version: 2 },
  { no: "248-1", name: "メガバンギラス", version: 2, isMega: true },
  { no: "249", name: "ルギア", version: 2 },
  { no: "250", name: "ホウオウ", version: 2 },
  { no: "251", name: "セレビィ", version: 2 },
  { no: "252", name: "キモリ", version: 3 },
  { no: "253", name: "ジュプトル", version: 3 },
  { no: "254", name: "ジュカイン", version: 3 },
  { no: "254-1", name: "メガジュカイン", version: 3, isMega: true },
  { no: "255", name: "アチャモ", version: 3 },
  { no: "256", name: "ワカシャモ", version: 3 },
  { no: "257", name: "バシャーモ", version: 3 },
  { no: "257-1", name: "メガバシャーモ", version: 3, isMega: true },
  { no: "258", name: "ミズゴロウ", version: 3 },
  { no: "259", name: "ヌマクロー", version: 3 },
  { no: "260", name: "ラグラージ", version: 3 },
  { no: "260-1", name: "メガラグラージ", version: 3, isMega: true },
  { no: "261", name: "ポチエナ", version: 3 },
  { no: "262", name: "グラエナ", version: 3 },
  { no: "263", name: "ジグザグマ", version: 3 },
  {
    no: "263-1",
    name: "ジグザグマ",
    name2: "ガラルのすがた",
    version: 3,
    isRegion: true,
  },
  { no: "264", name: "マッスグマ", version: 3 },
  {
    no: "264-1",
    name: "マッスグマ",
    name2: "ガラルのすがた",
    version: 3,
    isRegion: true,
  },
  { no: "265", name: "ケムッソ", version: 3 },
  { no: "266", name: "カラサリス", version: 3 },
  { no: "267", name: "アゲハント", version: 3 },
  { no: "268", name: "マユルド", version: 3 },
  { no: "269", name: "ドクケイル", version: 3 },
  { no: "270", name: "ハスボー", version: 3 },
  { no: "271", name: "ハスブレロ", version: 3 },
  { no: "272", name: "ルンパッパ", version: 3 },
  { no: "273", name: "タネボー", version: 3 },
  { no: "274", name: "コノハナ", version: 3 },
  { no: "275", name: "ダーテング", version: 3 },
  { no: "276", name: "スバメ", version: 3 },
  { no: "277", name: "オオスバメ", version: 3 },
  { no: "278", name: "キャモメ", version: 3 },
  { no: "279", name: "ペリッパー", version: 3 },
  { no: "280", name: "ラルトス", version: 3 },
  { no: "281", name: "キルリア", version: 3 },
  { no: "282", name: "サーナイト", version: 3 },
  { no: "282-1", name: "メガサーナイト", version: 3, isMega: true },
  { no: "283", name: "アメタマ", version: 3 },
  { no: "284", name: "アメモース", version: 3 },
  { no: "285", name: "キノココ", version: 3 },
  { no: "286", name: "キノガッサ", version: 3 },
  { no: "287", name: "ナマケロ", version: 3 },
  { no: "288", name: "ヤルキモノ", version: 3 },
  { no: "289", name: "ケッキング", version: 3 },
  { no: "290", name: "ツチニン", version: 3 },
  { no: "291", name: "テッカニン", version: 3 },
  { no: "292", name: "ヌケニン", version: 3 },
  { no: "293", name: "ゴニョニョ", version: 3 },
  { no: "294", name: "ドゴーム", version: 3 },
  { no: "295", name: "バクオング", version: 3 },
  { no: "296", name: "マクノシタ", version: 3 },
  { no: "297", name: "ハリテヤマ", version: 3 },
  { no: "298", name: "ルリリ", version: 3 },
  { no: "299", name: "ノズパス", version: 3 },
  { no: "300", name: "エネコ", version: 3 },
  { no: "301", name: "エネコロロ", version: 3 },
  { no: "302", name: "ヤミラミ", version: 3 },
  { no: "302-1", name: "メガヤミラミ", version: 3, isMega: true },
  { no: "303", name: "クチート", version: 3 },
  { no: "303-1", name: "メガクチート", version: 3, isMega: true },
  { no: "304", name: "ココドラ", version: 3 },
  { no: "305", name: "コドラ", version: 3 },
  { no: "306", name: "ボスゴドラ", version: 3 },
  { no: "306-1", name: "メガボスゴドラ", version: 3, isMega: true },
  { no: "307", name: "アサナン", version: 3 },
  { no: "308", name: "チャーレム", version: 3 },
  { no: "308-1", name: "メガチャーレム", version: 3, isMega: true },
  { no: "309", name: "ラクライ", version: 3 },
  { no: "310", name: "ライボルト", version: 3 },
  { no: "310-1", name: "メガライボルト", version: 3, isMega: true },
  { no: "311", name: "プラスル", version: 3 },
  { no: "312", name: "マイナン", version: 3 },
  { no: "313", name: "バルビート", version: 3 },
  { no: "314", name: "イルミーゼ", version: 3 },
  { no: "315", name: "ロゼリア", version: 3 },
  { no: "316", name: "ゴクリン", version: 3 },
  { no: "317", name: "マルノーム", version: 3 },
  { no: "318", name: "キバニア", version: 3 },
  { no: "319", name: "サメハダー", version: 3 },
  { no: "319-1", name: "メガサメハダー", version: 3, isMega: true },
  { no: "320", name: "ホエルコ", version: 3 },
  { no: "321", name: "ホエルオー", version: 3 },
  { no: "322", name: "ドンメル", version: 3 },
  { no: "323", name: "バクーダ", version: 3 },
  { no: "323-1", name: "メガバクーダ", version: 3, isMega: true },
  { no: "324", name: "コータス", version: 3 },
  { no: "325", name: "バネブー", version: 3 },
  { no: "326", name: "ブーピッグ", version: 3 },
  { no: "327", name: "パッチール", version: 3 },
  { no: "328", name: "ナックラー", version: 3 },
  { no: "329", name: "ビブラーバ", version: 3 },
  { no: "330", name: "フライゴン", version: 3 },
  { no: "331", name: "サボネア", version: 3 },
  { no: "332", name: "ノクタス", version: 3 },
  { no: "333", name: "チルット", version: 3 },
  { no: "334", name: "チルタリス", version: 3 },
  { no: "334-1", name: "メガチルタリス", version: 3, isMega: true },
  { no: "335", name: "ザングース", version: 3 },
  { no: "336", name: "ハブネーク", version: 3 },
  { no: "337", name: "ルナトーン", version: 3 },
  { no: "338", name: "ソルロック", version: 3 },
  { no: "339", name: "ドジョッチ", version: 3 },
  { no: "340", name: "ナマズン", version: 3 },
  { no: "341", name: "ヘイガニ", version: 3 },
  { no: "342", name: "シザリガー", version: 3 },
  { no: "343", name: "ヤジロン", version: 3 },
  { no: "344", name: "ネンドール", version: 3 },
  { no: "345", name: "リリーラ", version: 3 },
  { no: "346", name: "ユレイドル", version: 3 },
  { no: "347", name: "アノプス", version: 3 },
  { no: "348", name: "アーマルド", version: 3 },
  { no: "349", name: "ヒンバス", version: 3 },
  { no: "350", name: "ミロカロス", version: 3 },
  { no: "351", name: "ポワルン", version: 3 },
  // { no: "351-1", name: "ポワルン", version: 3 },
  // { no: "351-2", name: "ポワルン", version: 3 },
  // { no: "351-3", name: "ポワルン", version: 3 },
  { no: "352", name: "カクレオン", version: 3 },
  { no: "353", name: "カゲボウズ", version: 3 },
  { no: "354", name: "ジュペッタ", version: 3 },
  { no: "354-1", name: "メガジュペッタ", version: 3, isMega: true },
  { no: "355", name: "ヨマワル", version: 3 },
  { no: "356", name: "サマヨール", version: 3 },
  { no: "357", name: "トロピウス", version: 3 },
  { no: "358", name: "チリーン", version: 3 },
  { no: "359", name: "アブソル", version: 3 },
  { no: "359-1", name: "メガアブソル", version: 3, isMega: true },
  { no: "360", name: "ソーナノ", version: 3 },
  { no: "361", name: "ユキワラシ", version: 3 },
  { no: "362", name: "オニゴーリ", version: 3 },
  { no: "362-1", name: "メガオニゴーリ", version: 3, isMega: true },
  { no: "363", name: "タマザラシ", version: 3 },
  { no: "364", name: "トドグラー", version: 3 },
  { no: "365", name: "トドゼルガ", version: 3 },
  { no: "366", name: "パールル", version: 3 },
  { no: "367", name: "ハンテール", version: 3 },
  { no: "368", name: "サクラビス", version: 3 },
  { no: "369", name: "ジーランス", version: 3 },
  { no: "370", name: "ラブカス", version: 3 },
  { no: "371", name: "タツベイ", version: 3 },
  { no: "372", name: "コモルー", version: 3 },
  { no: "373", name: "ボーマンダ", version: 3 },
  { no: "373-1", name: "メガボーマンダ", version: 3, isMega: true },
  { no: "374", name: "ダンバル", version: 3 },
  { no: "375", name: "メタング", version: 3 },
  { no: "376", name: "メタグロス", version: 3 },
  { no: "376-1", name: "メガメタグロス", version: 3, isMega: true },
  { no: "377", name: "レジロック", version: 3 },
  { no: "378", name: "レジアイス", version: 3 },
  { no: "379", name: "レジスチル", version: 3 },
  { no: "380", name: "ラティアス", version: 3 },
  { no: "380-1", name: "メガラティアス", version: 3, isMega: true },
  { no: "381", name: "ラティオス", version: 3 },
  { no: "381-1", name: "メガラティオス", version: 3, isMega: true },
  { no: "382", name: "カイオーガ", version: 3 },
  { no: "382-1", name: "ゲンシカイオーガ", version: 3, isMega: true },
  { no: "383", name: "グラードン", version: 3 },
  { no: "383-1", name: "ゲンシグラードン", version: 3, isMega: true },
  { no: "384", name: "レックウザ", version: 3 },
  { no: "385", name: "ジラーチ", version: 3 },
  {
    no: "386",
    name: "デオキシス",
    name2: "ノーマルフォルム",
    version: 3,
    isAnotherForm: true,
  },
  {
    no: "386-1",
    name: "デオキシス",
    name2: "アタックフォルム",
    version: 3,
    isAnotherForm: true,
  },
  {
    no: "386-2",
    name: "デオキシス",
    name2: "ディフェンスフォルム",
    version: 3,
    isAnotherForm: true,
  },
  {
    no: "386-3",
    name: "デオキシス",
    name2: "スピードフォルム",
    version: 3,
    isAnotherForm: true,
  },
  { no: "387", name: "ナエトル", version: 4 },
  { no: "388", name: "ハヤシガメ", version: 4 },
  { no: "389", name: "ドダイトス", version: 4 },
  { no: "390", name: "ヒコザル", version: 4 },
  { no: "391", name: "モウカザル", version: 4 },
  { no: "392", name: "ゴウカザル", version: 4 },
  { no: "393", name: "ポッチャマ", version: 4 },
  { no: "394", name: "ポッタイシ", version: 4 },
  { no: "395", name: "エンペルト", version: 4 },
  { no: "396", name: "ムックル", version: 4 },
  { no: "397", name: "ムクバード", version: 4 },
  { no: "398", name: "ムクホーク", version: 4 },
  { no: "399", name: "ビッパ", version: 4 },
  { no: "400", name: "ビーダル", version: 4 },
  { no: "401", name: "コロボーシ", version: 4 },
  { no: "402", name: "コロトック", version: 4 },
  { no: "403", name: "コリンク", version: 4 },
  { no: "404", name: "ルクシオ", version: 4 },
  { no: "405", name: "レントラー", version: 4 },
  { no: "406", name: "スボミー", version: 4 },
  { no: "407", name: "ロズレイド", version: 4 },
  { no: "408", name: "ズガイドス", version: 4 },
  { no: "409", name: "ラムパルド", version: 4 },
  { no: "410", name: "タテトプス", version: 4 },
  { no: "411", name: "トリデプス", version: 4 },
  {
    no: "412",
    name: "ミノムッチ",
    name2: "くさきのミノ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "412-1",
    name: "ミノムッチ",
    name2: "すなちのミノ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "412-2",
    name: "ミノムッチ",
    name2: "ごみのミノ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "413",
    name: "ミノマダム",
    name2: "くさきのミノ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "413-1",
    name: "ミノマダム",
    name2: "すなちのミノ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "413-2",
    name: "ミノマダム",
    name2: "ごみのミノ",
    version: 4,
    isAnotherForm: true,
  },
  { no: "414", name: "ガーメイル", version: 4 },
  { no: "415", name: "ミツハニー", version: 4 },
  { no: "416", name: "ビークイン", version: 4 },
  { no: "417", name: "パチリス", version: 4 },
  { no: "418", name: "ブイゼル", version: 4 },
  { no: "419", name: "フローゼル", version: 4 },
  { no: "420", name: "チェリンボ", version: 4 },
  {
    no: "421",
    name: "チェリム",
    name2: "ネガフォルム",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "421-1",
    name: "チェリム",
    name2: "ポジフォルム",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "422-",
    name: "カラナクシ",
    name2: "にしのうみ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "422-1",
    name: "カラナクシ",
    name2: "ひがしのうみ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "423",
    name: "トリトドン",
    name2: "にしのうみ",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "423-1",
    name: "トリトドン",
    name2: "ひがしのうみ",
    version: 4,
    isAnotherForm: true,
  },
  { no: "424", name: "エテボース", version: 4 },
  { no: "425", name: "フワンテ", version: 4 },
  { no: "426", name: "フワライド", version: 4 },
  { no: "427", name: "ミミロル", version: 4 },
  { no: "428", name: "ミミロップ", version: 4 },
  { no: "428-1", name: "メガミミロップ", version: 4, isMega: true },
  { no: "429", name: "ムウマージ", version: 4 },
  { no: "430", name: "ドンカラス", version: 4 },
  { no: "431", name: "ニャルマー", version: 4 },
  { no: "432", name: "ブニャット", version: 4 },
  { no: "433", name: "リーシャン", version: 4 },
  { no: "434", name: "スカンプー", version: 4 },
  { no: "435", name: "スカタンク", version: 4 },
  { no: "436", name: "ドーミラー", version: 4 },
  { no: "437", name: "ドータクン", version: 4 },
  { no: "438", name: "ウソハチ", version: 4 },
  { no: "439", name: "マネネ", version: 4 },
  { no: "440", name: "ピンプク", version: 4 },
  { no: "441", name: "ペラップ", version: 4 },
  { no: "442", name: "ミカルゲ", version: 4 },
  { no: "443", name: "フカマル", version: 4 },
  { no: "444", name: "ガバイト", version: 4 },
  { no: "445", name: "ガブリアス", version: 4 },
  { no: "445-1", name: "メガガブリアス", version: 4, isMega: true },
  { no: "446", name: "ゴンベ", version: 4 },
  { no: "447", name: "リオル", version: 4 },
  { no: "448", name: "ルカリオ", version: 4 },
  { no: "448-1", name: "メガルカリオ", version: 4, isMega: true },
  { no: "449", name: "ヒポポタス", version: 4 },
  { no: "450", name: "カバルドン", version: 4 },
  { no: "451", name: "スコルピ", version: 4 },
  { no: "452", name: "ドラピオン", version: 4 },
  { no: "453", name: "グレッグル", version: 4 },
  { no: "454", name: "ドクロッグ", version: 4 },
  { no: "455", name: "マスキッパ", version: 4 },
  { no: "456", name: "ケイコウオ", version: 4 },
  { no: "457", name: "ネオラント", version: 4 },
  { no: "458", name: "タマンタ", version: 4 },
  { no: "459", name: "ユキカブリ", version: 4 },
  { no: "460", name: "ユキノオー", version: 4 },
  { no: "460-1", name: "メガユキノオー", version: 4, isMega: true },
  { no: "461", name: "マニューラ", version: 4 },
  { no: "462", name: "ジバコイル", version: 4 },
  { no: "463", name: "ベロベルト", version: 4 },
  { no: "464", name: "ドサイドン", version: 4 },
  { no: "465", name: "モジャンボ", version: 4 },
  { no: "466", name: "エレキブル", version: 4 },
  { no: "467", name: "ブーバーン", version: 4 },
  { no: "468", name: "トゲキッス", version: 4 },
  { no: "469", name: "メガヤンマ", version: 4 },
  { no: "470", name: "リーフィア", version: 4 },
  { no: "471", name: "グレイシア", version: 4 },
  { no: "472", name: "グライオン", version: 4 },
  { no: "473", name: "マンムー", version: 4 },
  {
    no: "474",
    name: "ポリゴンZ",
    version: 4,
    anotherAnswer: { name: "ポリゴンゼット" },
  },
  { no: "475", name: "エルレイド", version: 4 },
  { no: "475-1", name: "メガエルレイド", version: 4, isMega: true },
  { no: "476", name: "ダイノーズ", version: 4 },
  { no: "477", name: "ヨノワール", version: 4 },
  { no: "478", name: "ユキメノコ", version: 4 },
  {
    no: "479",
    name: "ロトム",
    name2: "ロトムのすがた",
    version: 4,
    isAnotherForm: true,
    anotherAnswer: { name: "ロトム", name2: "ノーマルフォルム" },
  },
  {
    no: "479-1",
    name: "ロトム",
    name2: "ヒートロトム",
    version: 4,
    isAnotherForm: true,
    anotherAnswer: { name: "ロトム", name2: "ヒートフォルム" },
  },
  {
    no: "479-2",
    name: "ロトム",
    name2: "ウォッシュロトム",
    version: 4,
    isAnotherForm: true,
    anotherAnswer: { name: "ロトム", name2: "ウォッシュフォルム" },
  },
  {
    no: "479-3",
    name: "ロトム",
    name2: "フロストロトム",
    version: 4,
    isAnotherForm: true,
    anotherAnswer: { name: "ロトム", name2: "フロストフォルム" },
  },
  {
    no: "479-4",
    name: "ロトム",
    name2: "スピンロトム",
    version: 4,
    isAnotherForm: true,
    anotherAnswer: { name: "ロトム", name2: "スピンフォルム" },
  },
  {
    no: "479-5",
    name: "ロトム",
    name2: "カットロトム",
    version: 4,
    isAnotherForm: true,
    anotherAnswer: { name: "ロトム", name2: "カットフォルム" },
  },
  { no: "480", name: "ユクシー", version: 4 },
  { no: "481", name: "エムリット", version: 4 },
  { no: "482", name: "アグノム", version: 4 },
  { no: "483", name: "ディアルガ", version: 4 },
  {
    no: "483-1",
    name: "ディアルガ",
    name2: "オリジンフォルム",
    version: 4,
    isAnotherForm: true,
  },
  { no: "484", name: "パルキア", version: 4 },
  {
    no: "484-1",
    name: "パルキア",
    name2: "オリジンフォルム",
    version: 4,
    isAnotherForm: true,
  },
  { no: "485", name: "ヒードラン", version: 4 },
  { no: "486", name: "レジギガス", version: 4 },
  {
    no: "487",
    name: "ギラティナ",
    name2: "アナザーフォルム",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "487-1",
    name: "ギラティナ",
    name2: "オリジンフォルム",
    version: 4,
    isAnotherForm: true,
  },
  { no: "488", name: "クレセリア", version: 4 },
  { no: "489", name: "フィオネ", version: 4 },
  { no: "490", name: "マナフィ", version: 4 },
  { no: "491", name: "ダークライ", version: 4 },
  {
    no: "492",
    name: "シェイミ",
    name2: "ランドフォルム",
    version: 4,
    isAnotherForm: true,
  },
  {
    no: "492-1",
    name: "シェイミ",
    name2: "スカイフォルム",
    version: 4,
    isAnotherForm: true,
  },
  { no: "493", name: "アルセウス", version: 4 },
  { no: "494", name: "ビクティニ", version: 5 },
  { no: "495", name: "ツタージャ", version: 5 },
  { no: "496", name: "ジャノビー", version: 5 },
  { no: "497", name: "ジャローダ", version: 5 },
  { no: "498", name: "ポカブ", version: 5 },
  { no: "499", name: "チャオブー", version: 5 },
  { no: "500", name: "エンブオー", version: 5 },
  { no: "501", name: "ミジュマル", version: 5 },
  { no: "502", name: "フタチマル", version: 5 },
  { no: "503", name: "ダイケンキ", version: 5 },
  {
    no: "503-1",
    name: "ダイケンキ",
    name2: "ヒスイのすがた",
    version: 5,
    isRegion: true,
  },
  { no: "504", name: "ミネズミ", version: 5 },
  { no: "505", name: "ミルホッグ", version: 5 },
  { no: "506", name: "ヨーテリー", version: 5 },
  { no: "507", name: "ハーデリア", version: 5 },
  { no: "508", name: "ムーランド", version: 5 },
  { no: "509", name: "チョロネコ", version: 5 },
  { no: "510", name: "レパルダス", version: 5 },
  { no: "511", name: "ヤナップ", version: 5 },
  { no: "512", name: "ヤナッキー", version: 5 },
  { no: "513", name: "バオップ", version: 5 },
  { no: "514", name: "バオッキー", version: 5 },
  { no: "515", name: "ヒヤップ", version: 5 },
  { no: "516", name: "ヒヤッキー", version: 5 },
  { no: "517", name: "ムンナ", version: 5 },
  { no: "518", name: "ムシャーナ", version: 5 },
  { no: "519", name: "マメパト", version: 5 },
  { no: "520", name: "ハトーボー", version: 5 },
  {
    no: "521",
    name: "ケンホロウ",
    name2: "オスのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "521-1",
    name: "ケンホロウ",
    name2: "メスのすがた",
    version: 5,
    isAnotherForm: true,
  },
  { no: "522", name: "シママ", version: 5 },
  { no: "523", name: "ゼブライカ", version: 5 },
  { no: "524", name: "ダンゴロ", version: 5 },
  { no: "525", name: "ガントル", version: 5 },
  { no: "526", name: "ギガイアス", version: 5 },
  { no: "527", name: "コロモリ", version: 5 },
  { no: "528", name: "ココロモリ", version: 5 },
  { no: "529", name: "モグリュー", version: 5 },
  { no: "530", name: "ドリュウズ", version: 5 },
  { no: "531", name: "タブンネ", version: 5 },
  { no: "531-1", name: "メガタブンネ", version: 5, isMega: true },
  { no: "532", name: "ドッコラー", version: 5 },
  { no: "533", name: "ドテッコツ", version: 5 },
  { no: "534", name: "ローブシン", version: 5 },
  { no: "535", name: "オタマロ", version: 5 },
  { no: "536", name: "ガマガル", version: 5 },
  { no: "537", name: "ガマゲロゲ", version: 5 },
  { no: "538", name: "ナゲキ", version: 5 },
  { no: "539", name: "ダゲキ", version: 5 },
  { no: "540", name: "クルミル", version: 5 },
  { no: "541", name: "クルマユ", version: 5 },
  { no: "542", name: "ハハコモリ", version: 5 },
  { no: "543", name: "フシデ", version: 5 },
  { no: "544", name: "ホイーガ", version: 5 },
  { no: "545", name: "ペンドラー", version: 5 },
  { no: "546", name: "モンメン", version: 5 },
  { no: "547", name: "エルフーン", version: 5 },
  { no: "548", name: "チュリネ", version: 5 },
  { no: "549", name: "ドレディア", version: 5 },
  {
    no: "549-1",
    name: "ドレディア",
    name2: "ヒスイのすがた",
    version: 5,
    isRegion: true,
  },
  {
    no: "550",
    name: "バスラオ",
    name2: "あかすじのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "550-1",
    name: "バスラオ",
    name2: "あおすじのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "550-2",
    name: "バスラオ",
    name2: "しろすじのすがた",
    version: 5,
    isAnotherForm: true,
  },
  { no: "551", name: "メグロコ", version: 5 },
  { no: "552", name: "ワルビル", version: 5 },
  { no: "553", name: "ワルビアル", version: 5 },
  { no: "554", name: "ダルマッカ", version: 5 },
  {
    no: "554-1",
    name: "ダルマッカ",
    name2: "ガラルのすがた",
    version: 5,
    isRegion: true,
  },
  {
    no: "555",
    name: "ヒヒダルマ",
    name2: "ノーマルモード",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "555-1",
    name: "ヒヒダルマ",
    name2: "ダルマモード",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "555-2",
    name: "ヒヒダルマ",
    name2: "ガラルのすがた",
    version: 5,
    isRegion: true,
  },
  {
    no: "555-3",
    name: "ヒヒダルマ",
    name2: "ガラルのすがた",
    name3: "ダルマモード",
    version: 5,
    isRegion: true,
    isAnotherForm: true,
  },
  { no: "556", name: "マラカッチ", version: 5 },
  { no: "557", name: "イシズマイ", version: 5 },
  { no: "558", name: "イワパレス", version: 5 },
  { no: "559", name: "ズルッグ", version: 5 },
  { no: "560", name: "ズルズキン", version: 5 },
  { no: "561", name: "シンボラー", version: 5 },
  { no: "562", name: "デスマス", version: 5 },
  {
    no: "562-1",
    name: "デスマス",
    name2: "ガラルのすがた",
    version: 5,
    isRegion: true,
  },
  { no: "563", name: "デスカーン", version: 5 },
  { no: "564", name: "プロトーガ", version: 5 },
  { no: "565", name: "アバゴーラ", version: 5 },
  { no: "566", name: "アーケン", version: 5 },
  { no: "567", name: "アーケオス", version: 5 },
  { no: "568", name: "ヤブクロン", version: 5 },
  { no: "569", name: "ダストダス", version: 5 },
  {
    no: "569-1",
    name: "ダストダス",
    name2: "キョダイマックスのすがた",
    version: 5,
    isGigantic: true,
  },
  { no: "570", name: "ゾロア", version: 5 },
  {
    no: "570-1",
    name: "ゾロア",
    name2: "ヒスイのすがた",
    version: 5,
    isRegion: true,
  },
  { no: "571", name: "ゾロアーク", version: 5 },
  {
    no: "571-1",
    name: "ゾロアーク",
    name2: "ヒスイのすがた",
    version: 5,
    isRegion: true,
  },
  { no: "572", name: "チラーミィ", version: 5 },
  { no: "573", name: "チラチーノ", version: 5 },
  { no: "574", name: "ゴチム", version: 5 },
  { no: "575", name: "ゴチミル", version: 5 },
  { no: "576", name: "ゴチルゼル", version: 5 },
  { no: "577", name: "ユニラン", version: 5 },
  { no: "578", name: "ダブラン", version: 5 },
  { no: "579", name: "ランクルス", version: 5 },
  { no: "580", name: "コアルヒー", version: 5 },
  { no: "581", name: "スワンナ", version: 5 },
  { no: "582", name: "バニプッチ", version: 5 },
  { no: "583", name: "バニリッチ", version: 5 },
  { no: "584", name: "バイバニラ", version: 5 },
  {
    no: "585",
    name: "シキジカ",
    name2: "はるのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "585-1",
    name: "シキジカ",
    name2: "なつのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "585-2",
    name: "シキジカ",
    name2: "あきのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "585-3",
    name: "シキジカ",
    name2: "ふゆのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "586",
    name: "メブキジカ",
    name2: "はるのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "586-1",
    name: "メブキジカ",
    name2: "なつのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "586-2",
    name: "メブキジカ",
    name2: "あきのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "586-3",
    name: "メブキジカ",
    name2: "ふゆのすがた",
    version: 5,
    isAnotherForm: true,
  },
  { no: "587", name: "エモンガ", version: 5 },
  { no: "588", name: "カブルモ", version: 5 },
  { no: "589", name: "シュバルゴ", version: 5 },
  { no: "590", name: "タマゲタケ", version: 5 },
  { no: "591", name: "モロバレル", version: 5 },
  {
    no: "592",
    name: "プルリル",
    name2: "オスのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "592-1",
    name: "プルリル",
    name2: "メスのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "593",
    name: "ブルンゲル",
    name2: "オスのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "593-1",
    name: "ブルンゲル",
    name2: "メスのすがた",
    version: 5,
    isAnotherForm: true,
  },
  { no: "594", name: "ママンボウ", version: 5 },
  { no: "595", name: "バチュル", version: 5 },
  { no: "596", name: "デンチュラ", version: 5 },
  { no: "597", name: "テッシード", version: 5 },
  { no: "598", name: "ナットレイ", version: 5 },
  { no: "599", name: "ギアル", version: 5 },
  { no: "600", name: "ギギアル", version: 5 },
  { no: "601", name: "ギギギアル", version: 5 },
  { no: "602", name: "シビシラス", version: 5 },
  { no: "603", name: "シビビール", version: 5 },
  { no: "604", name: "シビルドン", version: 5 },
  { no: "605", name: "リグレー", version: 5 },
  { no: "606", name: "オーベム", version: 5 },
  { no: "607", name: "ヒトモシ", version: 5 },
  { no: "608", name: "ランプラー", version: 5 },
  { no: "609", name: "シャンデラ", version: 5 },
  { no: "610", name: "キバゴ", version: 5 },
  { no: "611", name: "オノンド", version: 5 },
  { no: "612", name: "オノノクス", version: 5 },
  { no: "613", name: "クマシュン", version: 5 },
  { no: "614", name: "ツンベアー", version: 5 },
  { no: "615", name: "フリージオ", version: 5 },
  { no: "616", name: "チョボマキ", version: 5 },
  { no: "617", name: "アギルダー", version: 5 },
  { no: "618", name: "マッギョ", version: 5 },
  {
    no: "618-1",
    name: "マッギョ",
    name2: "ガラルのすがた",
    version: 5,
    isRegion: true,
  },
  { no: "619", name: "コジョフー", version: 5 },
  { no: "620", name: "コジョンド", version: 5 },
  { no: "621", name: "クリムガン", version: 5 },
  { no: "622", name: "ゴビット", version: 5 },
  { no: "623", name: "ゴルーグ", version: 5 },
  { no: "624", name: "コマタナ", version: 5 },
  { no: "625", name: "キリキザン", version: 5 },
  { no: "626", name: "バッフロン", version: 5 },
  { no: "627", name: "ワシボン", version: 5 },
  { no: "628", name: "ウォーグル", version: 5 },
  {
    no: "628-1",
    name: "ウォーグル",
    name2: "ヒスイのすがた",
    version: 5,
    isRegion: true,
  },
  { no: "629", name: "バルチャイ", version: 5 },
  { no: "630", name: "バルジーナ", version: 5 },
  { no: "631", name: "クイタラン", version: 5 },
  { no: "632", name: "アイアント", version: 5 },
  { no: "633", name: "モノズ", version: 5 },
  { no: "634", name: "ジヘッド", version: 5 },
  { no: "635", name: "サザンドラ", version: 5 },
  { no: "636", name: "メラルバ", version: 5 },
  { no: "637", name: "ウルガモス", version: 5 },
  { no: "638", name: "コバルオン", version: 5 },
  { no: "639", name: "テラキオン", version: 5 },
  { no: "640", name: "ビリジオン", version: 5 },
  {
    no: "641",
    name: "トルネロス",
    name2: "けしんフォルム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "641-1",
    name: "トルネロス",
    name2: "れいじゅうフォルム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "642",
    name: "ボルトロス",
    name2: "けしんフォルム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "642-1",
    name: "ボルトロス",
    name2: "れいじゅうフォルム",
    version: 5,
    isAnotherForm: true,
  },
  { no: "643", name: "レシラム", version: 5 },
  { no: "644", name: "ゼクロム", version: 5 },
  {
    no: "645",
    name: "ランドロス",
    name2: "けしんフォルム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "645-1",
    name: "ランドロス",
    name2: "れいじゅうフォルム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "646",
    name: "キュレム",
    name2: "キュレムのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "646-1",
    name: "キュレム",
    name2: "ホワイトキュレム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "646-2",
    name: "キュレム",
    name2: "ブラックキュレム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "647",
    name: "ケルディオ",
    name2: "いつものすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "647-1",
    name: "ケルディオ",
    name2: "かくごのすがた",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "648",
    name: "メロエッタ",
    name2: "ボイスフォルム",
    version: 5,
    isAnotherForm: true,
  },
  {
    no: "648-1",
    name: "メロエッタ",
    name2: "ステップフォルム",
    version: 5,
    isAnotherForm: true,
  },
  { no: "649", name: "ゲノセクト", version: 5 },
  { no: "650", name: "ハリマロン", version: 6 },
  { no: "651", name: "ハリボーグ", version: 6 },
  { no: "652", name: "ブリガロン", version: 6 },
  { no: "653", name: "フォッコ", version: 6 },
  { no: "654", name: "テールナー", version: 6 },
  { no: "655", name: "マフォクシー", version: 6 },
  { no: "656", name: "ケロマツ", version: 6 },
  { no: "657", name: "ゲコガシラ", version: 6 },
  { no: "658", name: "ゲッコウガ", version: 6 },
  { no: "659", name: "ホルビー", version: 6 },
  { no: "660", name: "ホルード", version: 6 },
  { no: "661", name: "ヤヤコマ", version: 6 },
  { no: "662", name: "ヒノヤコマ", version: 6 },
  { no: "663", name: "ファイアロー", version: 6 },
  { no: "664", name: "コフキムシ", version: 6 },
  { no: "665", name: "コフーライ", version: 6 },
  { no: "666", name: "ビビヨン", version: 6 },
  { no: "667", name: "シシコ", version: 6 },
  {
    no: "668",
    name: "カエンジシ",
    name2: "オスのすがた",
    version: 6,
    isAnotherForm: true,
  },
  {
    no: "668-1",
    name: "カエンジシ",
    name2: "メスのすがた",
    version: 6,
    isAnotherForm: true,
  },
  { no: "669", name: "フラベベ", version: 6 },
  { no: "670", name: "フラエッテ", version: 6 },
  { no: "671", name: "フラージェス", version: 6 },
  { no: "672", name: "メェークル", version: 6 },
  { no: "673", name: "ゴーゴート", version: 6 },
  { no: "674", name: "ヤンチャム", version: 6 },
  { no: "675", name: "ゴロンダ", version: 6 },
  { no: "676", name: "トリミアン", version: 6 },
  { no: "677", name: "ニャスパー", version: 6 },
  {
    no: "678",
    name: "ニャオニクス",
    name2: "オスのすがた",
    version: 6,
    isAnotherForm: true,
  },
  {
    no: "678-1",
    name: "ニャオニクス",
    name2: "メスのすがた",
    version: 6,
    isAnotherForm: true,
  },
  { no: "679", name: "ヒトツキ", version: 6 },
  { no: "680", name: "ニダンギル", version: 6 },
  {
    no: "681",
    name: "ギルガルド",
    name2: "シールドフォルム",
    version: 6,
    isAnotherForm: true,
  },
  {
    no: "681-1",
    name: "ギルガルド",
    name2: "ブレードフォルム",
    version: 6,
    isAnotherForm: true,
  },
  { no: "682", name: "シュシュプ", version: 6 },
  { no: "683", name: "フレフワン", version: 6 },
  { no: "684", name: "ペロッパフ", version: 6 },
  { no: "685", name: "ペロリーム", version: 6 },
  { no: "686", name: "マーイーカ", version: 6 },
  { no: "687", name: "カラマネロ", version: 6 },
  { no: "688", name: "カメテテ", version: 6 },
  { no: "689", name: "ガメノデス", version: 6 },
  { no: "690", name: "クズモー", version: 6 },
  { no: "691", name: "ドラミドロ", version: 6 },
  { no: "692", name: "ウデッポウ", version: 6 },
  { no: "693", name: "ブロスター", version: 6 },
  { no: "694", name: "エリキテル", version: 6 },
  { no: "695", name: "エレザード", version: 6 },
  { no: "696", name: "チゴラス", version: 6 },
  { no: "697", name: "ガチゴラス", version: 6 },
  { no: "698", name: "アマルス", version: 6 },
  { no: "699", name: "アマルルガ", version: 6 },
  { no: "700", name: "ニンフィア", version: 6 },
  { no: "701", name: "ルチャブル", version: 6 },
  { no: "702", name: "デデンネ", version: 6 },
  { no: "703", name: "メレシー", version: 6 },
  { no: "704", name: "ヌメラ", version: 6 },
  { no: "705", name: "ヌメイル", version: 6 },
  {
    no: "705-1",
    name: "ヌメイル",
    name2: "ヒスイのすがた",
    version: 6,
    isRegion: true,
  },
  { no: "706", name: "ヌメルゴン", version: 6 },
  {
    no: "706-1",
    name: "ヌメルゴン",
    name2: "ヒスイのすがた",
    version: 6,
    isRegion: true,
  },
  { no: "707", name: "クレッフィ", version: 6 },
  { no: "708", name: "ボクレー", version: 6 },
  { no: "709", name: "オーロット", version: 6 },
  { no: "710", name: "バケッチャ", version: 6 },
  { no: "711", name: "パンプジン", version: 6 },
  { no: "712", name: "カチコール", version: 6 },
  { no: "713", name: "クレベース", version: 6 },
  {
    no: "713-1",
    name: "クレベース",
    name2: "ヒスイのすがた",
    version: 6,
    isRegion: true,
  },
  { no: "714", name: "オンバット", version: 6 },
  { no: "715", name: "オンバーン", version: 6 },
  { no: "716", name: "ゼルネアス", version: 6 },
  { no: "717", name: "イベルタル", version: 6 },
  {
    no: "718",
    name: "ジガルデ",
    name2: "５０％フォルム",
    version: 6,
    isAnotherForm: true,
    anotherAnswer: { name: "ジガルデ", name2: "５０パーセントフォルム" },
  },
  {
    no: "718-1",
    name: "ジガルデ",
    name2: "１０％フォルム",
    version: 6,
    isAnotherForm: true,
    anotherAnswer: { name: "ジガルデ", name2: "１０パーセントフォルム" },
  },
  {
    no: "718-2",
    name: "ジガルデ",
    name2: "パーフェクトフォルム",
    version: 6,
    isAnotherForm: true,
  },
  { no: "719", name: "ディアンシー", version: 6 },
  { no: "719-1", name: "メガディアンシー", version: 6, isMega: true },
  {
    no: "720",
    name: "フーパ",
    name2: "いましめられしフーパ",
    version: 6,
    isAnotherForm: true,
  },
  {
    no: "720-1",
    name: "フーパ",
    name2: "ときはなたれしフーパ",
    version: 6,
    isAnotherForm: true,
  },
  { no: "721", name: "ボルケニオン", version: 6 },
  { no: "722", name: "モクロー", version: 7 },
  { no: "723", name: "フクスロー", version: 7 },
  { no: "724", name: "ジュナイパー", version: 7 },
  {
    no: "724-1",
    name: "ジュナイパー",
    name2: "ヒスイのすがた",
    version: 7,
    isRegion: true,
  },
  { no: "725", name: "ニャビー", version: 7 },
  { no: "726", name: "ニャヒート", version: 7 },
  { no: "727", name: "ガオガエン", version: 7 },
  { no: "728", name: "アシマリ", version: 7 },
  { no: "729", name: "オシャマリ", version: 7 },
  { no: "730", name: "アシレーヌ", version: 7 },
  { no: "731", name: "ツツケラ", version: 7 },
  { no: "732", name: "ケララッパ", version: 7 },
  { no: "733", name: "ドデカバシ", version: 7 },
  { no: "734", name: "ヤングース", version: 7 },
  { no: "735", name: "デカグース", version: 7 },
  { no: "736", name: "アゴジムシ", version: 7 },
  { no: "737", name: "デンヂムシ", version: 7 },
  { no: "738", name: "クワガノン", version: 7 },
  { no: "739", name: "マケンカニ", version: 7 },
  { no: "740", name: "ケケンカニ", version: 7 },
  {
    no: "741",
    name: "オドリドリ",
    name2: "めらめらスタイル",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "741-1",
    name: "オドリドリ",
    name2: "ぱちぱちスタイル",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "741-2",
    name: "オドリドリ",
    name2: "ふらふらスタイル",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "741-3",
    name: "オドリドリ",
    name2: "まいまいスタイル",
    version: 7,
    isAnotherForm: true,
  },
  { no: "742", name: "アブリー", version: 7 },
  { no: "743", name: "アブリボン", version: 7 },
  { no: "744", name: "イワンコ", version: 7 },
  {
    no: "745",
    name: "ルガルガン",
    name2: "まひるのすがた",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "745-1",
    name: "ルガルガン",
    name2: "まよなかのすがた",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "745-2",
    name: "ルガルガン",
    name2: "たそがれのすがた",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "746",
    name: "ヨワシ",
    name2: "たんどくのすがた",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "746-1",
    name: "ヨワシ",
    name2: "むれたすがた",
    version: 7,
    isAnotherForm: true,
  },
  { no: "747", name: "ヒドイデ", version: 7 },
  { no: "748", name: "ドヒドイデ", version: 7 },
  { no: "749", name: "ドロバンコ", version: 7 },
  { no: "750", name: "バンバドロ", version: 7 },
  { no: "751", name: "シズクモ", version: 7 },
  { no: "752", name: "オニシズクモ", version: 7 },
  { no: "753", name: "カリキリ", version: 7 },
  { no: "754", name: "ラランテス", version: 7 },
  { no: "755", name: "ネマシュ", version: 7 },
  { no: "756", name: "マシェード", version: 7 },
  { no: "757", name: "ヤトウモリ", version: 7 },
  { no: "758", name: "エンニュート", version: 7 },
  { no: "759", name: "ヌイコグマ", version: 7 },
  { no: "760", name: "キテルグマ", version: 7 },
  { no: "761", name: "アマカジ", version: 7 },
  { no: "762", name: "アママイコ", version: 7 },
  { no: "763", name: "アマージョ", version: 7 },
  { no: "764", name: "キュワワー", version: 7 },
  { no: "765", name: "ヤレユータン", version: 7 },
  { no: "766", name: "ナゲツケサル", version: 7 },
  { no: "767", name: "コソクムシ", version: 7 },
  { no: "768", name: "グソクムシャ", version: 7 },
  { no: "769", name: "スナバァ", version: 7 },
  { no: "770", name: "シロデスナ", version: 7 },
  { no: "771", name: "ナマコブシ", version: 7 },
  { no: "772", name: "タイプ:", version: 7 },
  { no: "773", name: "シルヴァディ", version: 7 },
  {
    no: "774",
    name: "メテノ",
    name2: "りゅうせいのすがた",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "774-1",
    name: "メテノ",
    name2: "あかいろのコア",
    version: 7,
    isAnotherForm: true,
  },
  { no: "775", name: "ネッコアラ", version: 7 },
  { no: "776", name: "バクガメス", version: 7 },
  { no: "777", name: "トゲデマル", version: 7 },
  { no: "778", name: "ミミッキュ", version: 7 },
  { no: "779", name: "ハギギシリ", version: 7 },
  { no: "780", name: "ジジーロン", version: 7 },
  { no: "781", name: "ダダリン", version: 7 },
  { no: "782", name: "ジャラコ", version: 7 },
  { no: "783", name: "ジャランゴ", version: 7 },
  { no: "784", name: "ジャラランガ", version: 7 },
  {
    no: "785",
    name: "カプ・コケコ",
    version: 7,
    anotherAnswer: { name: "カプコケコ" },
  },
  {
    no: "786",
    name: "カプ・テテフ",
    version: 7,
    anotherAnswer: { name: "カプテテフ" },
  },
  {
    no: "787",
    name: "カプ・ブルル",
    version: 7,
    anotherAnswer: { name: "カプブルル" },
  },
  {
    no: "788",
    name: "カプ・レヒレ",
    version: 7,
    anotherAnswer: { name: "カプレヒレ" },
  },
  { no: "789", name: "コスモッグ", version: 7 },
  { no: "790", name: "コスモウム", version: 7 },
  { no: "791", name: "ソルガレオ", version: 7 },
  { no: "792", name: "ルナアーラ", version: 7 },
  { no: "793", name: "ウツロイド", version: 7 },
  { no: "794", name: "マッシブーン", version: 7 },
  { no: "795", name: "フェローチェ", version: 7 },
  { no: "796", name: "デンジュモク", version: 7 },
  { no: "797", name: "テッカグヤ", version: 7 },
  { no: "798", name: "カミツルギ", version: 7 },
  { no: "799", name: "アクジキング", version: 7 },
  { no: "800", name: "ネクロズマ", version: 7 },
  {
    no: "800-1",
    name: "ネクロズマ",
    name2: "たそがれのたてがみ",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "800-2",
    name: "ネクロズマ",
    name2: "あかつきのつばさ",
    version: 7,
    isAnotherForm: true,
  },
  {
    no: "800-3",
    name: "ネクロズマ",
    name2: "ウルトラネクロズマ",
    version: 7,
    isAnotherForm: true,
  },
  { no: "801", name: "マギアナ", version: 7 },
  { no: "802", name: "マーシャドー", version: 7 },
  { no: "803", name: "ベベノム", version: 7 },
  { no: "804", name: "アーゴヨン", version: 7 },
  { no: "805", name: "ツンデツンデ", version: 7 },
  { no: "806", name: "ズガドーン", version: 7 },
  { no: "807", name: "ゼラオラ", version: 7 },
  { no: "808", name: "メルタン", version: 7 },
  { no: "809", name: "メルメタル", version: 7 },
  {
    no: "809-1",
    name: "メルメタル",
    name2: "キョダイマックスのすがた",
    version: 7,
    isGigantic: true,
  },
  { no: "810", name: "サルノリ", version: 8 },
  { no: "811", name: "バチンキー", version: 8 },
  { no: "812", name: "ゴリランダー", version: 8 },
  {
    no: "812-1",
    name: "ゴリランダー",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "813", name: "ヒバニー", version: 8 },
  { no: "814", name: "ラビフット", version: 8 },
  { no: "815", name: "エースバーン", version: 8 },
  {
    no: "815-1",
    name: "エースバーン",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "816", name: "メッソン", version: 8 },
  { no: "817", name: "ジメレオン", version: 8 },
  { no: "818", name: "インテレオン", version: 8 },
  {
    no: "818-1",
    name: "インテレオン",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "819", name: "ホシガリス", version: 8 },
  { no: "820", name: "ヨクバリス", version: 8 },
  { no: "821", name: "ココガラ", version: 8 },
  { no: "822", name: "アオガラス", version: 8 },
  { no: "823", name: "アーマーガア", version: 8 },
  {
    no: "823-1",
    name: "アーマーガア",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "824", name: "サッチムシ", version: 8 },
  { no: "825", name: "レドームシ", version: 8 },
  { no: "826", name: "イオルブ", version: 8 },
  { no: "827", name: "クスネ", version: 8 },
  { no: "828", name: "フォクスライ", version: 8 },
  { no: "829", name: "ヒメンカ", version: 8 },
  { no: "830", name: "ワタシラガ", version: 8 },
  { no: "831", name: "ウールー", version: 8 },
  { no: "832", name: "バイウールー", version: 8 },
  { no: "833", name: "カムカメ", version: 8 },
  { no: "834", name: "カジリガメ", version: 8 },
  {
    no: "834-1",
    name: "カジリガメ",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "835", name: "ワンパチ", version: 8 },
  { no: "836", name: "パルスワン", version: 8 },
  { no: "837", name: "タンドン", version: 8 },
  { no: "838", name: "トロッゴン", version: 8 },
  { no: "839", name: "セキタンザン", version: 8 },
  {
    no: "839-1",
    name: "セキタンザン",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "840", name: "カジッチュ", version: 8 },
  { no: "841", name: "アップリュー", version: 8 },
  {
    no: "841-1",
    name: "アップリュー",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
    anotherAnswer: { name: "タルップル", name2: "キョダイマックスのすがた" },
  },
  { no: "842", name: "タルップル", version: 8 },
  { no: "843", name: "スナヘビ", version: 8 },
  { no: "844", name: "サダイジャ", version: 8 },
  {
    no: "844-1",
    name: "サダイジャ",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "845", name: "ウッウ", version: 8 },
  { no: "846", name: "サシカマス", version: 8 },
  { no: "847", name: "カマスジョー", version: 8 },
  { no: "848", name: "エレズン", version: 8 },
  {
    no: "849",
    name: "ストリンダー",
    name2: "ハイなすがた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "849-1",
    name: "ストリンダー",
    name2: "ローなすがた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "849-2",
    name: "ストリンダー",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "850", name: "ヤクデ", version: 8 },
  { no: "851", name: "マルヤクデ", version: 8 },
  {
    no: "851-1",
    name: "マルヤクデ",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "852", name: "タタッコ", version: 8 },
  { no: "853", name: "オトスパス", version: 8 },
  { no: "854", name: "ヤバチャ", version: 8 },
  { no: "855", name: "ポットデス", version: 8 },
  { no: "856", name: "ミブリム", version: 8 },
  { no: "857", name: "テブリム", version: 8 },
  { no: "858", name: "ブリムオン", version: 8 },
  {
    no: "858-1",
    name: "ブリムオン",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "859", name: "ベロバー", version: 8 },
  { no: "860", name: "ギモー", version: 8 },
  { no: "861", name: "オーロンゲ", version: 8 },
  {
    no: "861-1",
    name: "オーロンゲ",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "862", name: "タチフサグマ", version: 8 },
  { no: "863", name: "ニャイキング", version: 8 },
  { no: "864", name: "サニゴーン", version: 8 },
  { no: "865", name: "ネギガナイト", version: 8 },
  { no: "866", name: "バリコオル", version: 8 },
  { no: "867", name: "デスバーン", version: 8 },
  { no: "868", name: "マホミル", version: 8 },
  { no: "869", name: "マホイップ", version: 8 },
  {
    no: "869-1",
    name: "マホイップ",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "870", name: "タイレーツ", version: 8 },
  { no: "871", name: "バチンウニ", version: 8 },
  { no: "872", name: "ユキハミ", version: 8 },
  { no: "873", name: "モスノウ", version: 8 },
  { no: "874", name: "イシヘンジン", version: 8 },
  {
    no: "875",
    name: "コオリッポ",
    name2: "アイスフェイス",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "875-1",
    name: "コオリッポ",
    name2: "ナイスフェイス",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "876",
    name: "イエッサン",
    name2: "オスのすがた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "876-1",
    name: "イエッサン",
    name2: "メスのすがた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "877",
    name: "モルペコ",
    name2: "まんぷくもよう",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "877-1",
    name: "モルペコ",
    name2: "はらぺこもよう",
    version: 8,
    isAnotherForm: true,
  },
  { no: "878", name: "ゾウドウ", version: 8 },
  { no: "879", name: "ダイオウドウ", version: 8 },
  {
    no: "879-1",
    name: "ダイオウドウ",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "880", name: "パッチラゴン", version: 8 },
  { no: "881", name: "パッチルドン", version: 8 },
  { no: "882", name: "ウオノラゴン", version: 8 },
  { no: "883", name: "ウオチルドン", version: 8 },
  { no: "884", name: "ジュラルドン", version: 8 },
  {
    no: "884-1",
    name: "ジュラルドン",
    name2: "キョダイマックスのすがた",
    version: 8,
    isGigantic: true,
  },
  { no: "885", name: "ドラメシヤ", version: 8 },
  { no: "886", name: "ドロンチ", version: 8 },
  { no: "887", name: "ドラパルト", version: 8 },
  {
    no: "888",
    name: "ザシアン",
    name2: "れきせんのゆうしゃ",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "888-1",
    name: "ザシアン",
    name2: "けんのおう",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "889",
    name: "ザマゼンタ",
    name2: "れきせんのゆうしゃ",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "889-1",
    name: "ザマゼンタ",
    name2: "たてのおう",
    version: 8,
    isAnotherForm: true,
  },
  { no: "890", name: "ムゲンダイナ", version: 8 },
  { no: "891", name: "ダクマ", version: 8 },
  {
    no: "892",
    name: "ウーラオス",
    name2: "いちげきのかた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "892-1",
    name: "ウーラオス",
    name2: "れんげきのかた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "892-2",
    name: "ウーラオス",
    name2: "いちげきのかた",
    name3: "キョダイマックスのすがた",
    version: 8,
    isAnotherForm: true,
    isGigantic: true,
  },
  {
    no: "892-3",
    name: "ウーラオス",
    name2: "れんげきのかた",
    name3: "キョダイマックスのすがた",
    version: 8,
    isAnotherForm: true,
    isGigantic: true,
  },
  { no: "893", name: "ザルード", version: 8 },
  { no: "894", name: "レジエレキ", version: 8 },
  { no: "895", name: "レジドラゴ", version: 8 },
  { no: "896", name: "ブリザポス", version: 8 },
  { no: "897", name: "レイスポス", version: 8 },
  { no: "898", name: "バドレックス", version: 8 },
  {
    no: "898-1",
    name: "バドレックス",
    name2: "はくばじょうのすがた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "898-2",
    name: "バドレックス",
    name2: "こくばじょうのすがた",
    version: 8,
    isAnotherForm: true,
  },
  { no: "899", name: "アヤシシ", version: 8 },
  { no: "900", name: "バサギリ", version: 8 },
  { no: "901", name: "ガチグマ", version: 8 },
  {
    no: "902",
    name: "イダイトウ",
    name2: "オスのすがた",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "902-1",
    name: "イダイトウ",
    name2: "メスのすがた",
    version: 8,
    isAnotherForm: true,
  },
  { no: "903", name: "オオニューラ", version: 8 },
  { no: "904", name: "ハリーマン", version: 8 },
  {
    no: "905",
    name: "ラブトロス",
    name2: "けしんフォルム",
    version: 8,
    isAnotherForm: true,
  },
  {
    no: "905-1",
    name: "ラブトロス",
    name2: "れいじゅうフォルム",
    version: 8,
    isAnotherForm: true,
  },
  { no: "906", name: "ニャオハ", version: 9 },
  { no: "907", name: "ニャローテ", version: 9 },
  { no: "908", name: "マスカーニャ", version: 9 },
  { no: "909", name: "ホゲータ", version: 9 },
  { no: "910", name: "アチゲータ", version: 9 },
  { no: "911", name: "ラウドボーン", version: 9 },
  { no: "912", name: "クワッス", version: 9 },
  { no: "913", name: "ウェルカモ", version: 9 },
  { no: "914", name: "ウェーニバル", version: 9 },
  { no: "915", name: "グルトン", version: 9 },
  {
    no: "916",
    name: "パフュートン",
    name2: "オスのすがた",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "916-1",
    name: "パフュートン",
    name2: "メスのすがた",
    version: 9,
    isAnotherForm: true,
  },
  { no: "917", name: "タマンチュラ", version: 9 },
  { no: "918", name: "ワナイダー", version: 9 },
  { no: "919", name: "マメバッタ", version: 9 },
  { no: "920", name: "エクスレッグ", version: 9 },
  { no: "921", name: "パモ", version: 9 },
  { no: "922", name: "パモット", version: 9 },
  { no: "923", name: "パーモット", version: 9 },
  { no: "924", name: "ワッカネズミ", version: 9 },
  {
    no: "925",
    name: "イッカネズミ",
    name2: "４ひきかぞく",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "925-1",
    name: "イッカネズミ",
    name2: "３びきかぞく",
    version: 9,
    isAnotherForm: true,
  },
  { no: "926", name: "パピモッチ", version: 9 },
  { no: "927", name: "バウッツェル", version: 9 },
  { no: "928", name: "ミニーブ", version: 9 },
  { no: "929", name: "オリーニョ", version: 9 },
  { no: "930", name: "オリーヴァ", version: 9 },
  {
    no: "931",
    name: "イキリンコ",
    name2: "グリーンフェザー",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "931-1",
    name: "イキリンコ",
    name2: "ブルーフェザー",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "931-2",
    name: "イキリンコ",
    name2: "イエローフェザー",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "931-3",
    name: "イキリンコ",
    name2: "ホワイトフェザー",
    version: 9,
    isAnotherForm: true,
  },
  { no: "932", name: "コジオ", version: 9 },
  { no: "933", name: "ジオヅム", version: 9 },
  { no: "934", name: "キョジオーン", version: 9 },
  { no: "935", name: "カルボウ", version: 9 },
  { no: "936", name: "グレンアルマ", version: 9 },
  { no: "937", name: "ソウブレイズ", version: 9 },
  { no: "938", name: "ズピカ", version: 9 },
  { no: "939", name: "ハラバリー", version: 9 },
  { no: "940", name: "カイデン", version: 9 },
  { no: "941", name: "タイカイデン", version: 9 },
  { no: "942", name: "オラチフ", version: 9 },
  { no: "943", name: "マフィティフ", version: 9 },
  { no: "944", name: "シルシュルー", version: 9 },
  { no: "945", name: "タギングル", version: 9 },
  { no: "946", name: "アノクサ", version: 9 },
  { no: "947", name: "アノホラグサ", version: 9 },
  { no: "948", name: "ノノクラゲ", version: 9 },
  { no: "949", name: "リククラゲ", version: 9 },
  { no: "950", name: "ガケガニ", version: 9 },
  { no: "951", name: "カプサイジ", version: 9 },
  { no: "952", name: "スコヴィラン", version: 9 },
  { no: "953", name: "シガロコ", version: 9 },
  { no: "954", name: "ベラカス", version: 9 },
  { no: "955", name: "ヒラヒナ", version: 9 },
  { no: "956", name: "クエスパトラ", version: 9 },
  { no: "957", name: "カヌチャン", version: 9 },
  { no: "958", name: "ナカヌチャン", version: 9 },
  { no: "959", name: "デカヌチャン", version: 9 },
  { no: "960", name: "ウミディグダ", version: 9 },
  { no: "961", name: "ウミトリオ", version: 9 },
  { no: "962", name: "オトシドリ", version: 9 },
  { no: "963", name: "ナミイルカ", version: 9 },
  {
    no: "964",
    name: "イルカマン",
    name2: "ナイーブフォルム",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "964-1",
    name: "イルカマン",
    name2: "マイティフォルム",
    version: 9,
    isAnotherForm: true,
  },
  { no: "965", name: "ブロロン", version: 9 },
  { no: "966", name: "ブロロローム", version: 9 },
  { no: "967", name: "モトトカゲ", version: 9 },
  { no: "968", name: "ミミズズ", version: 9 },
  { no: "969", name: "キラーメ", version: 9 },
  { no: "970", name: "キラフロル", version: 9 },
  { no: "971", name: "ボチ", version: 9 },
  { no: "972", name: "ハカドッグ", version: 9 },
  { no: "973", name: "カラミンゴ", version: 9 },
  { no: "974", name: "アルクジラ", version: 9 },
  { no: "975", name: "ハルクジラ", version: 9 },
  { no: "976", name: "ミガルーサ", version: 9 },
  { no: "977", name: "ヘイラッシャ", version: 9 },
  {
    no: "978",
    name: "シャリタツ",
    name2: "そったすがた",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "978-1",
    name: "シャリタツ",
    name2: "たれたすがた",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "978-2",
    name: "シャリタツ",
    name2: "のびたすがた",
    version: 9,
    isAnotherForm: true,
  },
  { no: "979", name: "コノヨザル", version: 9 },
  { no: "980", name: "ドオー", version: 9 },
  { no: "981", name: "リキキリン", version: 9 },
  {
    no: "982",
    name: "ノココッチ",
    name2: "ふたふしフォルム",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "982-1",
    name: "ノココッチ",
    name2: "みつふしフォルム",
    version: 9,
    isAnotherForm: true,
  },
  { no: "983", name: "ドドゲザン", version: 9 },
  { no: "984", name: "イダイナキバ", version: 9 },
  { no: "985", name: "サケブシッポ", version: 9 },
  { no: "986", name: "アラブルタケ", version: 9 },
  { no: "987", name: "ハバタクカミ", version: 9 },
  { no: "988", name: "チヲハウハネ", version: 9 },
  { no: "989", name: "スナノケガワ", version: 9 },
  { no: "990", name: "テツノワダチ", version: 9 },
  { no: "991", name: "テツノツツミ", version: 9 },
  { no: "992", name: "テツノカイナ", version: 9 },
  { no: "993", name: "テツノコウベ", version: 9 },
  { no: "994", name: "テツノドクガ", version: 9 },
  { no: "995", name: "テツノイバラ", version: 9 },
  { no: "996", name: "セビエ", version: 9 },
  { no: "997", name: "セゴール", version: 9 },
  { no: "998", name: "セグレイブ", version: 9 },
  {
    no: "999",
    name: "コレクレー",
    name2: "はこフォルム",
    version: 9,
    isAnotherForm: true,
  },
  {
    no: "999-1",
    name: "コレクレー",
    name2: "とほフォルム",
    version: 9,
    isAnotherForm: true,
  },
  { no: "1000", name: "サーフゴー", version: 9 },
  { no: "1001", name: "チオンジェン", version: 9 },
  { no: "1002", name: "パオジアン", version: 9 },
  { no: "1003", name: "ディンルー", version: 9 },
  { no: "1004", name: "イーユイ", version: 9 },
  { no: "1005", name: "トドロクツキ", version: 9 },
  { no: "1006", name: "テツノブジン", version: 9 },
  { no: "1007", name: "コライドン", version: 9 },
];
