/**
 * このファイルの作り方
 * 1. 画像を用意する（リネームしてimage/pokemon に格納）
 * 2. wiki から対象の範囲をコピペして、{No, name} のリストをつくる（https://wiki.xn--rckteqa2e.com/wiki/%E3%83%9D%E3%82%B1%E3%83%A2%E3%83%B3%E4%B8%80%E8%A6%A7）
 *    ( で参照して削除すると、姿違いを除外してポケモンの名前だけにできる
 * 3. version を付与する
 * 4. メガやリージョンフォーム・キョダイマックスなどはポケモン図鑑を見ながら手入力で対応する（https://zukan.pokemon.co.jp/）
 */

export const POKEMONS: {
  no: string;
  name: string;
  version: number;
  name2?: string;
  isMega?: boolean;
  isGigantic?: boolean;
  isRegion?: boolean;
}[] = [
  { no: "1", name: "フシギダネ", version: 1 },
  { no: "2", name: "フシギソウ", version: 1 },
  { no: "3", name: "フシギバナ", version: 1 },
  { no: "3-1", name: "メガフシギバナ", version: 1, isMega: true },
  {
    no: "3-2",
    name: "フシギバナ",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "4", name: "ヒトカゲ", version: 1 },
  { no: "5", name: "リザード", version: 1 },
  { no: "6", name: "リザードン", version: 1 },
  { no: "6-1", name: "メガリザードンX", version: 1, isMega: true },
  { no: "6-2", name: "メガリザードンY", version: 1, isMega: true },
  {
    no: "6-3",
    name: "リザードン",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "7", name: "ゼニガメ", version: 1 },
  { no: "8", name: "カメール", version: 1 },
  { no: "9", name: "カメックス", version: 1 },
  { no: "9-1", name: "メガカメックス", version: 1, isMega: true },
  {
    no: "9-2",
    name: "カメックス",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "10", name: "キャタピー", version: 1 },
  { no: "11", name: "トランセル", version: 1 },
  { no: "12", name: "バタフリー", version: 1 },
  {
    no: "12-1",
    name: "バタフリー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "13", name: "ビードル", version: 1 },
  { no: "14", name: "コクーン", version: 1 },
  { no: "15", name: "スピアー", version: 1 },
  { no: "15-1", name: "メガスピアー", version: 1, isMega: true },
  { no: "16", name: "ポッポ", version: 1 },
  { no: "17", name: "ピジョン", version: 1 },
  { no: "18", name: "ピジョット", version: 1 },
  { no: "18-1", name: "メガピジョット", version: 1, isMega: true },
  { no: "19", name: "コラッタ", version: 1 },
  {
    no: "19-1",
    name: "コラッタ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "20", name: "ラッタ", version: 1 },
  {
    no: "20-1",
    name: "ラッタ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "21", name: "オニスズメ", version: 1 },
  { no: "22", name: "オニドリル", version: 1 },
  { no: "23", name: "アーボ", version: 1 },
  { no: "24", name: "アーボック", version: 1 },
  { no: "25", name: "ピカチュウ", version: 1 },
  {
    no: "25-1",
    name: "ピカチュウ",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "26", name: "ライチュウ", version: 1 },
  {
    no: "26-1",
    name: "ライチュウ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "27", name: "サンド", version: 1 },
  {
    no: "27-1",
    name: "サンド",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "28", name: "サンドパン", version: 1 },
  {
    no: "28-1",
    name: "サンドパン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "29", name: "ニドラン♀", version: 1 },
  { no: "30", name: "ニドリーナ", version: 1 },
  { no: "31", name: "ニドクイン", version: 1 },
  { no: "32", name: "ニドラン♂", version: 1 },
  { no: "33", name: "ニドリーノ", version: 1 },
  { no: "34", name: "ニドキング", version: 1 },
  { no: "35", name: "ピッピ", version: 1 },
  { no: "36", name: "ピクシー", version: 1 },
  { no: "37", name: "ロコン", version: 1 },
  {
    no: "37-1",
    name: "ロコン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "38", name: "キュウコン", version: 1 },
  {
    no: "38-1",
    name: "キュウコン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "39", name: "プリン", version: 1 },
  { no: "40", name: "プクリン", version: 1 },
  { no: "41", name: "ズバット", version: 1 },
  { no: "42", name: "ゴルバット", version: 1 },
  { no: "43", name: "ナゾノクサ", version: 1 },
  { no: "44", name: "クサイハナ", version: 1 },
  { no: "45", name: "ラフレシア", version: 1 },
  { no: "46", name: "パラス", version: 1 },
  { no: "47", name: "パラセクト", version: 1 },
  { no: "48", name: "コンパン", version: 1 },
  { no: "49", name: "モルフォン", version: 1 },
  { no: "50", name: "ディグダ", version: 1 },
  {
    no: "50-1",
    name: "ディグダ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "51", name: "ダグトリオ", version: 1 },
  {
    no: "51-1",
    name: "ダグトリオ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "52", name: "ニャース", version: 1 },
  {
    no: "52-1",
    name: "ニャース",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  {
    no: "52-2",
    name: "ニャース",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  {
    no: "52-3",
    name: "ニャース",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "53", name: "ペルシアン", version: 1 },
  {
    no: "53-1",
    name: "ペルシアン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "54", name: "コダック", version: 1 },
  { no: "55", name: "ゴルダック", version: 1 },
  { no: "56", name: "マンキー", version: 1 },
  { no: "57", name: "オコリザル", version: 1 },
  { no: "58", name: "ガーディ", version: 1 },
  {
    no: "58-1",
    name: "ガーディ",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "59", name: "ウインディ", version: 1 },
  {
    no: "59-1",
    name: "ウインディ",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "60", name: "ニョロモ", version: 1 },
  { no: "61", name: "ニョロゾ", version: 1 },
  { no: "62", name: "ニョロボン", version: 1 },
  { no: "63", name: "ケーシィ", version: 1 },
  { no: "64", name: "ユンゲラー", version: 1 },
  { no: "65", name: "フーディン", version: 1 },
  { no: "65-1", name: "メガフーディン", version: 1, isMega: true },
  { no: "66", name: "ワンリキー", version: 1 },
  { no: "67", name: "ゴーリキー", version: 1 },
  { no: "68", name: "カイリキー", version: 1 },
  {
    no: "68-1",
    name: "カイリキー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "69", name: "マダツボミ", version: 1 },
  { no: "70", name: "ウツドン", version: 1 },
  { no: "71", name: "ウツボット", version: 1 },
  { no: "72", name: "メノクラゲ", version: 1 },
  { no: "73", name: "ドククラゲ", version: 1 },
  { no: "74", name: "イシツブテ", version: 1 },
  {
    no: "74-1",
    name: "イシツブテ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "75", name: "ゴローン", version: 1 },
  {
    no: "75-1",
    name: "ゴローン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "76", name: "ゴローニャ", version: 1 },
  {
    no: "76-1",
    name: "ゴローニャ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "77", name: "ポニータ", version: 1 },
  {
    no: "77-1",
    name: "ポニータ",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "78", name: "ギャロップ", version: 1 },
  {
    no: "78-1",
    name: "ギャロップ",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "79", name: "ヤドン", version: 1 },
  {
    no: "79-1",
    name: "ヤドン",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "80", name: "ヤドラン", version: 1 },
  {
    no: "80-1",
    name: "ヤドラン",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "80-2", name: "メガヤドラン", version: 1, isMega: true },
  { no: "81", name: "コイル", version: 1 },
  { no: "82", name: "レアコイル", version: 1 },
  { no: "83", name: "カモネギ", version: 1 },
  {
    no: "83-1",
    name: "カモネギ",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "84", name: "ドードー", version: 1 },
  { no: "85", name: "ドードリオ", version: 1 },
  { no: "86", name: "パウワウ", version: 1 },
  { no: "87", name: "ジュゴン", version: 1 },
  { no: "88", name: "ベトベター", version: 1 },
  {
    no: "88-1",
    name: "ベトベター",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "89", name: "ベトベトン", version: 1 },
  {
    no: "89-1",
    name: "ベトベトン",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "90", name: "シェルダー", version: 1 },
  { no: "91", name: "パルシェン", version: 1 },
  { no: "92", name: "ゴース", version: 1 },
  { no: "93", name: "ゴースト", version: 1 },
  { no: "94", name: "ゲンガー", version: 1 },
  { no: "94-1", name: "メガゲンガー", version: 1, isMega: true },
  {
    no: "94-2",
    name: "ゲンガー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "95", name: "イワーク", version: 1 },
  { no: "96", name: "スリープ", version: 1 },
  { no: "97", name: "スリーパー", version: 1 },
  { no: "98", name: "クラブ", version: 1 },
  { no: "99", name: "キングラー", version: 1 },
  {
    no: "99-1",
    name: "キングラー",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "100", name: "ビリリダマ", version: 1 },
  {
    no: "100-1",
    name: "ビリリダマ",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "101", name: "マルマイン", version: 1 },
  {
    no: "101-1",
    name: "マルマイン",
    name2: "ヒスイのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "102", name: "タマタマ", version: 1 },
  { no: "103", name: "ナッシー", version: 1 },
  {
    no: "103-1",
    name: "ナッシー",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "104", name: "カラカラ", version: 1 },
  { no: "105", name: "ガラガラ", version: 1 },
  {
    no: "105-1",
    name: "ガラガラ",
    name2: "アローラのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "106", name: "サワムラー", version: 1 },
  { no: "107", name: "エビワラー", version: 1 },
  { no: "108", name: "ベロリンガ", version: 1 },
  { no: "109", name: "ドガース", version: 1 },
  { no: "110", name: "マタドガス", version: 1 },
  {
    no: "110-1",
    name: "マタドガス",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "111", name: "サイホーン", version: 1 },
  { no: "112", name: "サイドン", version: 1 },
  { no: "113", name: "ラッキー", version: 1 },
  { no: "114", name: "モンジャラ", version: 1 },
  { no: "115", name: "ガルーラ", version: 1 },
  { no: "115-1", name: "メガガルーラ", version: 1, isMega: true },
  { no: "116", name: "タッツー", version: 1 },
  { no: "117", name: "シードラ", version: 1 },
  { no: "118", name: "トサキント", version: 1 },
  { no: "119", name: "アズマオウ", version: 1 },
  { no: "120", name: "ヒトデマン", version: 1 },
  { no: "121", name: "スターミー", version: 1 },
  { no: "122", name: "バリヤード", version: 1 },
  {
    no: "122-1",
    name: "バリヤード",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "123", name: "ストライク", version: 1 },
  { no: "124", name: "ルージュラ", version: 1 },
  { no: "125", name: "エレブー", version: 1 },
  { no: "126", name: "ブーバー", version: 1 },
  { no: "127", name: "カイロス", version: 1 },
  { no: "127-1", name: "メガカイロス", version: 1, isMega: true },
  { no: "128", name: "ケンタロス", version: 1 },
  {
    no: "128-1",
    name: "ケンタロス",
    name2: "パルデアのすがた・コンバットしゅ",
    version: 1,
    isRegion: true,
  },
  {
    no: "128-2",
    name: "ケンタロス",
    name2: "パルデアのすがた・ブレイズしゅ",
    version: 1,
    isRegion: true,
  },
  {
    no: "128-3",
    name: "ケンタロス",
    name2: "パルデアのすがた・ウォーターしゅ",
    version: 1,
    isRegion: true,
  },
  { no: "129", name: "コイキング", version: 1 },
  { no: "130", name: "ギャラドス", version: 1 },
  { no: "130-1", name: "メガギャラドス", version: 1, isMega: true },
  { no: "131", name: "ラプラス", version: 1 },
  {
    no: "131-1",
    name: "ラプラス",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "132", name: "メタモン", version: 1 },
  { no: "133", name: "イーブイ", version: 1 },
  {
    no: "133-1",
    name: "イーブイ",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "134", name: "シャワーズ", version: 1 },
  { no: "135", name: "サンダース", version: 1 },
  { no: "136", name: "ブースター", version: 1 },
  { no: "137", name: "ポリゴン", version: 1 },
  { no: "138", name: "オムナイト", version: 1 },
  { no: "139", name: "オムスター", version: 1 },
  { no: "140", name: "カブト", version: 1 },
  { no: "141", name: "カブトプス", version: 1 },
  { no: "142", name: "プテラ", version: 1 },
  { no: "142-1", name: "メガプテラ", version: 1, isMega: true },
  { no: "143", name: "カビゴン", version: 1 },
  {
    no: "143-1",
    name: "カビゴン",
    name2: "キョダイマックスのすがた",
    version: 1,
    isGigantic: true,
  },
  { no: "144", name: "フリーザー", version: 1 },
  {
    no: "144-1",
    name: "フリーザー",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "145", name: "サンダー", version: 1 },
  {
    no: "145-1",
    name: "サンダー",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "146", name: "ファイヤー", version: 1 },
  {
    no: "146-1",
    name: "ファイヤー",
    name2: "ガラルのすがた",
    version: 1,
    isRegion: true,
  },
  { no: "147", name: "ミニリュウ", version: 1 },
  { no: "148", name: "ハクリュー", version: 1 },
  { no: "149", name: "カイリュー", version: 1 },
  { no: "150", name: "ミュウツー", version: 1 },
  { no: "150-1", name: "メガミュウツーX", version: 1, isMega: true },
  { no: "150-2", name: "メガミュウツーY", version: 1, isMega: true },
  { no: "151", name: "ミュウ", version: 1 },
  { no: "152", name: "チコリータ", version: 2 },
  { no: "153", name: "ベイリーフ", version: 2 },
  { no: "154", name: "メガニウム", version: 2 },
  { no: "155", name: "ヒノアラシ", version: 2 },
  { no: "156", name: "マグマラシ", version: 2 },
  { no: "157", name: "バクフーン", version: 2 },
  {
    no: "157-1",
    name: "バクフーン",
    name2: "ヒスイのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "158", name: "ワニノコ", version: 2 },
  { no: "159", name: "アリゲイツ", version: 2 },
  { no: "160", name: "オーダイル", version: 2 },
  { no: "161", name: "オタチ", version: 2 },
  { no: "162", name: "オオタチ", version: 2 },
  { no: "163", name: "ホーホー", version: 2 },
  { no: "164", name: "ヨルノズク", version: 2 },
  { no: "165", name: "レディバ", version: 2 },
  { no: "166", name: "レディアン", version: 2 },
  { no: "167", name: "イトマル", version: 2 },
  { no: "168", name: "アリアドス", version: 2 },
  { no: "169", name: "クロバット", version: 2 },
  { no: "170", name: "チョンチー", version: 2 },
  { no: "171", name: "ランターン", version: 2 },
  { no: "172", name: "ピチュー", version: 2 },
  { no: "173", name: "ピィ", version: 2 },
  { no: "174", name: "ププリン", version: 2 },
  { no: "175", name: "トゲピー", version: 2 },
  { no: "176", name: "トゲチック", version: 2 },
  { no: "177", name: "ネイティ", version: 2 },
  { no: "178", name: "ネイティオ", version: 2 },
  { no: "179", name: "メリープ", version: 2 },
  { no: "180", name: "モココ", version: 2 },
  { no: "181", name: "デンリュウ", version: 2 },
  { no: "181-1", name: "メガデンリュウ", version: 2, isMega: true },
  { no: "182", name: "キレイハナ", version: 2 },
  { no: "183", name: "マリル", version: 2 },
  { no: "184", name: "マリルリ", version: 2 },
  { no: "185", name: "ウソッキー", version: 2 },
  { no: "186", name: "ニョロトノ", version: 2 },
  { no: "187", name: "ハネッコ", version: 2 },
  { no: "188", name: "ポポッコ", version: 2 },
  { no: "189", name: "ワタッコ", version: 2 },
  { no: "190", name: "エイパム", version: 2 },
  { no: "191", name: "ヒマナッツ", version: 2 },
  { no: "192", name: "キマワリ", version: 2 },
  { no: "193", name: "ヤンヤンマ", version: 2 },
  { no: "194", name: "ウパー", version: 2 },
  {
    no: "194-1",
    name: "ウパー",
    name2: "パルデアのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "195", name: "ヌオー", version: 2 },
  { no: "196", name: "エーフィ", version: 2 },
  { no: "197", name: "ブラッキー", version: 2 },
  { no: "198", name: "ヤミカラス", version: 2 },
  { no: "199", name: "ヤドキング", version: 2 },
  {
    no: "199-1",
    name: "ヤドキング",
    name2: "ガラルのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "200", name: "ムウマ", version: 2 },
  { no: "201", name: "アンノーン", version: 2 },
  { no: "202", name: "ソーナンス", version: 2 },
  { no: "203", name: "キリンリキ", version: 2 },
  { no: "204", name: "クヌギダマ", version: 2 },
  { no: "205", name: "フォレトス", version: 2 },
  { no: "206", name: "ノコッチ", version: 2 },
  { no: "207", name: "グライガー", version: 2 },
  { no: "208", name: "ハガネール", version: 2 },
  { no: "208-1", name: "メガハガネール", version: 2, isMega: true },
  { no: "209", name: "ブルー", version: 2 },
  { no: "210", name: "グランブル", version: 2 },
  { no: "211", name: "ハリーセン", version: 2 },
  {
    no: "211-1",
    name: "ハリーセン",
    name2: "ヒスイのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "212", name: "ハッサム", version: 2 },
  { no: "212-1", name: "メガハッサム", version: 2, isMega: true },
  { no: "213", name: "ツボツボ", version: 2 },
  { no: "214", name: "ヘラクロス", version: 2 },
  { no: "214-1", name: "メガヘラクロス", version: 2, isMega: true },
  { no: "215", name: "ニューラ", version: 2 },
  {
    no: "215-1",
    name: "ニューラ",
    name2: "ヒスイのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "216", name: "ヒメグマ", version: 2 },
  { no: "217", name: "リングマ", version: 2 },
  { no: "218", name: "マグマッグ", version: 2 },
  { no: "219", name: "マグカルゴ", version: 2 },
  { no: "220", name: "ウリムー", version: 2 },
  { no: "221", name: "イノムー", version: 2 },
  { no: "222", name: "サニーゴ", version: 2 },
  {
    no: "222-1",
    name: "サニーゴ",
    name2: "ガラルのすがた",
    version: 2,
    isRegion: true,
  },
  { no: "223", name: "テッポウオ", version: 2 },
  { no: "224", name: "オクタン", version: 2 },
  { no: "225", name: "デリバード", version: 2 },
  { no: "226", name: "マンタイン", version: 2 },
  { no: "227", name: "エアームド", version: 2 },
  { no: "228", name: "デルビル", version: 2 },
  { no: "229", name: "ヘルガー", version: 2 },
  { no: "229-1", name: "メガヘルガー", version: 2, isMega: true },
  { no: "230", name: "キングドラ", version: 2 },
  { no: "231", name: "ゴマゾウ", version: 2 },
  { no: "232", name: "ドンファン", version: 2 },
  { no: "233", name: "ポリゴン2", version: 2 },
  { no: "234", name: "オドシシ", version: 2 },
  { no: "235", name: "ドーブル", version: 2 },
  { no: "236", name: "バルキー", version: 2 },
  { no: "237", name: "カポエラー", version: 2 },
  { no: "238", name: "ムチュール", version: 2 },
  { no: "239", name: "エレキッド", version: 2 },
  { no: "240", name: "ブビィ", version: 2 },
  { no: "241", name: "ミルタンク", version: 2 },
  { no: "242", name: "ハピナス", version: 2 },
  { no: "243", name: "ライコウ", version: 2 },
  { no: "244", name: "エンテイ", version: 2 },
  { no: "245", name: "スイクン", version: 2 },
  { no: "246", name: "ヨーギラス", version: 2 },
  { no: "247", name: "サナギラス", version: 2 },
  { no: "248", name: "バンギラス", version: 2 },
  { no: "248-1", name: "メガバンギラス", version: 2, isMega: true },
  { no: "249", name: "ルギア", version: 2 },
  { no: "250", name: "ホウオウ", version: 2 },
  { no: "251", name: "セレビィ", version: 2 },
  // { no: "252", name: "キモリ", version: 3 },
  // { no: "253", name: "ジュプトル", version: 3 },
  // { no: "254", name: "ジュカイン", version: 3 },
];
